name: kite-env

channels:
  - conda-forge
  - defaults

dependencies:
  - matplotlib=3.2
  - numpy=1.18.5
  - scipy=1.4.1
  - pytest=5.4.3
  - cmake=3.17.0
  - pip=20.0
  - python=3.8
  - hdf5=1.10.6
  - eigen=3.3.7
  - git=2.23
  - pip:
      - pybinding
      - quantum-kite-MAndelkovic
      - --no-binary=h5py h5py
      - --no-binary=h5py
      - h5py
